# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geek Girl Web Designs
email: geekgirlwebdesigns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web design with affordable rates and great turn around time!  Online web design or in person
  (locally) to Ohio.  References available.  Take a look around.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geekgirlwebdesigns.com" # the base hostname & protocol for your site
twitter_username: geekgirlwebdesigns
github_username:  geekgirl2017

# Build settings
markdown: kramdown
